File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/codecs.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/copy.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/copy_reg.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/encodings/__init__.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/encodings/aliases.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/encodings/utf_8.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/os/__init__.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/os/path.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/re.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/site.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/sre_compile.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/sre_constants.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/sre_parse.pyc
File cannot be opened for reading: /autofs/na4_sw/xk6/ddt/4.0/sles11.1_binary/lib/python2.6/types.pyc
The local tree node (ddt-treeserver) exited with error code 1.